// 画面に出る文言はすべてここに集める。
// 日本語を習いはじめた人でも読めるように、ひらがなとカタカナだけで書く（漢字は使わない）。
// 読みやすくするため、ことばの切れめに空白を入れる。ja.test.ts が漢字の混入を検査する。
export const ja = {
  appName: 'ごのみち',
  tagline: 'しずかに うつ、いご。',

  home: {
    play: 'たいきょく',
    playSub: 'コンピュータと、または ふたりで',
    tsumego: 'つめご',
    tsumegoSub: (done: number, total: number) => `${done} / ${total} もん せいかい`,
    resume: 'つづきから',
    resumeSub: (size: number, level: string, moveNo: number) => `${size}×${size}・${level}・${moveNo}てめ`,
    discard: 'すてる',
    discardAsk: 'ほぞんした たいきょくを すてますか？',
    discardBody: 'すてると、もとには もどせません。',
    discardYes: 'すてる',
    updateAvailable: 'あたらしい バージョンが あります',
    update: 'こうしん',
    rules: 'あそびかた',
    settings: 'せってい',
    record: (w: number, l: number, d: number) => `せいせき ${w}かち ${l}まけ${d ? ` ${d}ひきわけ` : ''}`,
  },

  setup: {
    title: 'たいきょくの せってい',
    board: 'ばんの おおきさ',
    boardOpt: { 9: '9×9', 13: '13×13', 19: '19×19' } as Record<number, string>,
    boardSub: { 9: 'はじめての ひとに', 13: 'ふつう', 19: 'ほんかく' } as Record<number, string>,
    opponent: 'あいて',
    ai: 'コンピュータ',
    local: 'ふたりで うつ',
    level: 'つよさ',
    levelName: { nyumon: 'にゅうもん', shokyu: 'しょきゅう', chukyu: 'ちゅうきゅう' } as Record<string, string>,
    levelSub: {
      nyumon: 'ルールを おぼえる',
      shokyu: 'すこし かんがえる',
      chukyu: 'じっくり かんがえる',
    } as Record<string, string>,
    color: 'あなたの いし',
    black: 'くろ',
    blackSub: 'さきに うつ',
    white: 'しろ',
    whiteSub: 'あとに うつ',
    random: 'おまかせ',
    handicap: 'おきいし',
    even: 'たがいせん',
    stones: (n: number) => `${n}こ`,
    komi: 'コミ',
    komiValue: (k: number) => (k === 0 ? 'なし' : k % 1 ? `${Math.floor(k)}もくはん` : `${k}もく`),
    start: 'はじめる',
    discardAsk: 'ちゅうだんした たいきょくを すてますか？',
    discardBody: 'あたらしい たいきょくを はじめると、ちゅうだんしていた たいきょくは きえます。',
    discardYes: 'すてて はじめる',
  },

  game: {
    back: 'もどる',
    you: 'あなた',
    computer: 'コンピュータ',
    black: 'くろ',
    white: 'しろ',
    blackTurn: 'くろの ばん',
    whiteTurn: 'しろの ばん',
    moveNo: (n: number) => `${n}てめ`,
    komi: (s: string) => `コミ ${s}`,
    prisoners: (n: number) => `アゲハマ ${n}`,
    prisonersLabel: 'アゲハマ',
    pass: 'パス',
    undo: 'まった',
    resign: 'とうりょう',
    thinking: 'かんがえちゅう',
    passed: (who: string) => `${who}が パスしました`,
    ko: 'コウです。ほかの ところに うってください',
    suicide: 'そこには うてません',
    resignAsk: 'とうりょうしますか？',
    resignBody: 'とうりょうすると、この たいきょくは まけに なります。',
    resignYes: 'とうりょうする',
    cancel: 'キャンセル',
    leaveAsk: 'たいきょくを ちゅうだんしますか？',
    leaveBody: 'つづきは ホームの「つづきから」で できます。',
    leaveYes: 'ちゅうだんする',
    keepPlaying: 'つづける',
    // おわりの しょり
    scoring: 'しにいしの かくにん',
    scoringHelp: 'しんでいる いしを タップして えらびます',
    estimating: 'はんてい ちゅう',
    autoDead: 'じどう はんてい',
    resume: 'たいきょくを つづける',
    finish: 'しゅうきょく',
    territory: 'じ',
    total: 'ごうけい',
    komiRow: 'コミ',
    // けっか
    resultTitle: 'しゅうきょく',
    resultBtn: 'けっか',
    winBy: (who: string, margin: string) => `${who}の ${margin} かち`,
    winResign: (who: string) => `${who}の かち（あいてが とうりょう）`,
    jigo: 'じご（ひきわけ）',
    againBtn: 'もういちど',
    homeBtn: 'ホームへ',
    reviewBtn: 'ばんを みる',
    youWin: 'あなたの かち',
    youLose: 'あなたの まけ',
    hint: 'ヒント',
    hinting: 'かんがえちゅう…',
    hintPass: 'パスが よさそうです',
    atari: 'アタリ',
    assistedNote: 'まった・ヒントを つかったので、せいせきには いれません',
    passAgain: 'もういちど P を おすと パスします',
    previewTap: 'もういちど タップすると、ここに おきます',
    moveLabel: (n: number, mark: string) => `${n}てめ ${mark}`,
    passLabel: 'パス',
    review: 'きふを みる',
    first: 'さいしょへ',
    prev: 'ひとつ もどる',
    next: 'ひとつ すすむ',
    lastMove: 'さいごへ',
    copySgf: 'きふを コピー',
    saveSgf: 'きふを ほぞん',
    copied: 'きふを コピーしました',
    copyFail: 'コピーできませんでした',
    saved: 'きふを ほぞんしました',
    announce: (n: number, mark: string) => `${n}てめ ${mark}`,
  },

  rules: {
    title: 'あそびかた',
    sections: [
      {
        head: 'かちまけの きめかた',
        body: 'くろと しろが かわりばんこに いしを おきます。 ひろい じんち（じ）を かこんだ ほうが かちです。 くろが さきに うちます。 おいた いしは うごかせません。',
      },
      {
        head: 'いしの おきかた',
        body: 'ばんの せんと せんが まじわる てんに、いしを おきます。 くろが さきに うち、そのあとは こうごに うちます。 うつ ところが ないとき、または うちたくない ときは「パス」を します。 おおきな ばんを ゆびで さわる ときは、1かい タップで ばしょを かくにんして、もう1かい おなじ ところを タップすると おけます。',
      },
      {
        head: 'こきゅうてん',
        body: 'いしの うえ、した、ひだり、みぎの あいている ところを「こきゅうてん」と いいます。 つながった いしは、こきゅうてんを わけあいます。',
        diagram: 'liberty',
      },
      {
        head: 'いしを とる',
        body: 'こきゅうてんが ぜんぶ あいての いしで ふさがれると、その いしは とられて ばんから きえます。 とった いしは「アゲハマ」として かぞえます。',
        diagram: 'capture',
      },
      {
        head: 'うてない ところ',
        body: 'うつと じぶんの いしの こきゅうてんが なくなる ところには うてません。 ただし、あいての いしを とれる ときは うてます。',
      },
      {
        head: 'コウ',
        body: 'おたがいに ひとつずつ とりあう かたちでは、とられた すぐあとに とりかえす ことは できません。 ほかの ところに ひとつ うってから、とりかえします。',
        diagram: 'ko',
      },
      {
        head: 'おわりと かぞえかた',
        body: 'りょうほうが つづけて パスすると おわりです。 しんでいる いしを とりのぞいて、かこんだ じの かずと アゲハマを あわせて くらべます。 しろには コミ（くろが さきに うつ ぶんの ハンデ）が たされます。',
      },
      {
        head: 'しにいしと セキ',
        body: 'おわりの とき、もう たすからない いしを「しにいし」と いいます。 この アプリは しにいしを じどうで えらびますが、まちがう ことも あるので、いしを タップして なおして ください。 おたがいに とりあえない かたちを「セキ」と いいます。 セキの いしは「しにいし」に しないで ください。 そこは どちらの じにも なりません。',
      },
      {
        head: 'おきいし',
        body: 'ちからに さが あるときは、よわい ほうが くろを もち、さいしょから いしを いくつか おいて はじめます。 これを「おきいし」と いいます。 おきいしの ときは、しろが さきに うちます。 この アプリでは、おきいしの ときの コミは「なし」です。',
      },
    ],
  },

  tsumego: {
    title: 'つめご',
    list: 'いちらん',
    problem: (n: number) => `だい${n}もん`,
    goal: (n: number) => `くろの ばん。 しろを とろう（${n}てまで）`,
    level: { 1: 'にゅうもん', 2: 'しょきゅう', 3: 'ちゅうきゅう' } as Record<number, string>,
    solved: 'せいかい',
    correct: 'せいかいです',
    wrong: 'その てでは とれません',
    wrongSub: 'ひとつ もどすか、はじめから やりなおしましょう',
    hint: 'ヒント',
    answer: 'こたえ',
    retry: 'やりなおし',
    undo: 'ひとつ もどす',
    next: 'つぎの もんだい',
    allDone: 'ぜんぶの もんだいを とけました。 おめでとう！',
    whitePassed: 'しろは パスしました',
    showing: 'せいかいの てじゅん',
    tap: 'くろの いってを うってください',
    alreadyThere: 'そこには もう いしが あります',
    progress: (done: number, total: number) => `${done} / ${total} もん せいかい`,
  },

  settings: {
    title: 'せってい',
    sound: 'こうかおん',
    vibrate: 'ぶるっと ふるえる',
    on: 'オン',
    off: 'オフ',
    data: 'ほぞんした データ',
    resetRecord: 'せいせきを けす',
    resetSolved: 'つめごの きろくを けす',
    resetAll: 'ぜんぶ けして はじめから',
    confirmAsk: 'ほんとうに けしますか？',
    confirmBody: 'けすと、もとには もどせません。',
    confirmYes: 'けす',
    about: 'このアプリに ついて',
    aboutText: 'ごのみちは、ひらがなと カタカナだけで あそべる いごの アプリです。',
    privacy: 'たいきょく・せってい・せいせきなどの データは、この たんまつの なかにだけ ほぞんされます。 そとには おくられません。',
    version: (v: string) => `バージョン ${v}`,
    license: 'ライセンス: MIT',
    source: 'ソースコード（GitHub）',
    fonts: 'もじ: Noto Sans JP・Noto Serif JP（SIL Open Font License）',
  },

  errorScreen: {
    title: 'もんだいが おきました',
    body: 'すみません。がめんを よみこみなおすと、なおる ことが あります。',
    reload: 'よみこみなおす',
    clearAndReload: 'ほぞんした データを ぜんぶ けして よみこみなおす',
  },

  aria: {
    board: 'ごばん',
    boardKeys: 'ごばん。やじるしキーで うごかして、エンターキーで おきます',
    stoneBlack: 'くろの いし',
    stoneWhite: 'しろの いし',
    pointEmpty: 'あき',
    back: 'もどる',
    soundOn: 'こうかおんを オフに する',
    soundOff: 'こうかおんを オンに する',
    fullscreenOn: 'ぜんがめんに する',
    fullscreenOff: 'ぜんがめんを おわる',
  },
};
